version: "2"
services:
  # redis:
  #   image: redis:5.0.5
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   command: redis-server

  taskcenter:
    image: taskcenter
    restart: always
    environment:
      - redis_host=172.17.0.1
    ports: 
      - 8000:80
